#!/usr/bin/python

import rethinkdb as r
conn=r.connect(host='localhost',
                port=28015,
                db='test'
                ).repl()

print r.db_list().run(conn)
# I names my table zoo becuase i was planning on watching zootopia 
# repalce test and zoo with your db and table names
zoo=r.db('test').table('zoo')
print "The total amount ofrows in the Test DB and Zoo table is"
print zoo.count().run(conn)
#check=zoo.wait(wait_for='ready_for_writes',timeout=2).run(conn)
#print check
#error="{u'ready': 1}"

if check == error:
        conn.close()


i=1
while i<5:
        zoo.wait(wait_for='ready_for_writes',timeout=10).run(conn)
        if check == error:
                conn.close()
        else:
		zoo.count().run.(conn)
#       print "Adding data"
#                zoo.insert({ 'name': 'Star Trek TNG', 'episodes': '178' }).run()
#       print "Current number:"
#       print zoo.count().run()
                print ".",

